version: "3.8"

services:
  endpoint:
    build:
      context: ./endpoint
      target: development
    restart: always
    volumes:
      - ./endpoint:/home/app
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"
