version: "3.8"

services:
  endpoint:
    build:
      context: ./endpoint
    restart: unless-stopped
    volumes:
      - ./endpoint:/home/app
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
