version: "3.8"

x-base: &base
  env_file:
    - .env.dev

services:
  endpoint:
    <<: *base
    build:
      context: ./endpoint
      target: development
    command: flask run
    restart: always
    volumes:
      - ./endpoint:/home/app
