version: "3.8"

#x-base: &base
#  env_file:
#    - .env.dev

services:
  v1:
    extends:
      file: common.yml
      service: endpoint
    environment:
      LOG_LEVEL: DEBUG
      #      SENTRY_DSN: https://pubjet@sentry.example.com/11
      ENDPOINT_PATH: v1
      MAX_CONTENT_LENGTH: 1024
#    command: gunicorn sapp:app -w 2 -k uvicorn.workers.UvicornWorker
    command: uvicorn --host 0.0.0.0 sapp:app
    expose:
      - 8000
    ports:
      - 8002:8000
    container_name: weatherlamp_server_v1
