version: "3.8"

services:
  endpoint:
    build:
      context: ./endpoint
    restart: unless-stopped
    volumes:
      - ./endpoint:/home/app
      # Single named volume for all app-written data (cache, history, error_dumps).
      # Mounted on top of the source bind-mount so Docker manages ownership correctly.
      - weatherlamp_data:/home/app/data
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "20m"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
